name: websites
version: 1.0.0
type: binary
entrypoint: ./target/relese/websites
env:
  - key: RUST_LOG
    value: "info"
  - key: HOST
    value: "127.0.0.1:10005"
  - key: DB_HOST
    value: "127.0.0.1"
  - key: DB_PORT
    value: "5432"
  - key: DB_DBNAME
    value: "websites"
  - key: DB_USER
    value: "websites_user"
  - key: DB_PASSWORD
    value: "Ruyual8uth0eivaef4oPhaegaeQuah5o"
  - key: DB_ROOT_CERT
    value: "/opt/cockroach/certs/ca.crt"
  - key: JWKS_HOST
    value: "auth-dev.peoplesmarkets.com"
  - key: JWKS_URL
    value: "https://auth-dev.peoplesmarkets.com/oauth/v2/keys"
  - key: MAIN_DOMAIN
    value: "peoplesmarkets.com"
  - key: FALLBACK_DOMAIN
    value: "fallback.peoplesmarkets.com"
  - key: ZITADEL_API_URL
    value: "https://auth-dev.peoplesmarkets.com"
  - key: ZITADEL_API_TOKEN
    value: "Bearer 0G-G-ELkPPlWR8bhAWKccr45prN-nDP-gxuu1lyKiZcmqS4FNejG93Q-dfUCWlppJkehtOk"
  - key: ZITADEL_PROJECT_ID
    value: "232051257500516520"
  - key: CLOUDFLARE_API_URL
    value: "https://api.cloudflare.com/client/v4"
  - key: CLOUDFLARE_ZONE_ID
    value: "ea9945aa1fad692fd7ab1f0cfedda555"
  - key: CLOUDFLARE_API_TOKEN
    value: "Bearer XO43Flxafj6kS3SxChTZm3s3MDfotRCJmKVYslzP"
  - key: BUCKET_NAME
    value: "dev-websites"
  - key: BUCKET_ENDPOINT
    value: "https://0d78eb8c22ee83b01fa99dd3efb348ae.r2.cloudflarestorage.com"
  - key: BUCKET_ACCESS_KEY_ID
    value: "1e4bc746ca9659e3a263aeed6fbcbb43"
  - key: BUCKET_SECRET_ACCESS_KEY
    value: "58f8b01f714eed82754df53676dfcb0f65fe79e2eb9dc3ada5a35573efb13a6f"
  - key: BUCKET_URL
    value: "https://objects-dev-websites.peoplesmarkets.com"
  - key: IMAGE_MAX_SIZE
    value: "2000000"
resources:
  memory: 256Mi
  cpu: 500m
networking:
  ports:
    - containerPort: 10005
      protocol: TCP
