CREATE TABLE pages (
  page_id SERIAL PRIMARY KEY,
  website_id VARCHAR NOT NULL REFERENCES websites(website_id),
  user_id VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  title VARCHAR NOT NULL,
  page_type VARCHAR NOT NULL,
  content_id VARCHAR NOT NULL
)